### ISSUE TITLE
술 엔티티 설계

### ISSUE THREAD

**Issue by whatasame** [woowatechcamp/soolsool#11]
liquors 테이블은 다음과 같이 구성된다. 
- id
- category
- region
- name
   - 길이가 최대 30자 까지 가능하다. 
- price
   - 길이가 최대 30자 까지 가능하다.
- brand
   - 길이가 최대 30자 까지 가능하다.
- image_url
   - 길이가 최대 255자 까지 가능하다.
- stock
  - 재고는 0 미만 일 수는 없다. 
- alcohol 
- volume
- create_at
- modified_at

regions 테이블은 다음과 같이 구성된다.
- id
- name 
  - 전국 팔도 기준이다.
  - 최대 20자 까지 가능하다. 
- created_at
- modified_at

categories 테이블은 다음과 같이 구성된다.
- id
- type
  - 제조 방식
  - 최대 20자 까지 가능하다. 
- created_at
- modified_at

**Comment by worldii** [comment]
현재 고민이 되는 부분이 카테고리 부분을 enum으로 해야 하는지 테이블로 해야하는지 고민이 들어요! 
백만개의 데이터가 있다고 가정했을지 카테고리를 가져오기 위해 조인하는 과정 vs 백만개 category String을 저장하여 메모리 낭비가 있을지 얘기해보면 좋을거같아요
https://careerly.co.kr/qnas/1100

근데 생각해보니까  전자가 맞는듯 ㅎㅎ  ㅋㅋㅋㄹㅎㅋㅋ

**Comment by whatasame** [comment]
closed by #37
