### ISSUE TITLE
장바구니 엔티티 설계

### ISSUE THREAD

**Issue by whatasame** [woowatechcamp/soolsool#13]
cart_liquors 테이블은 다음과 같이 구성된다. 
- id
- member_id
- liquor_id
- liquor_quantity
- created_at
- modified_at

**Comment by worldii** [comment]
장바구니 등록은 하나씩 추가하는 구조인가요 여러개 추가도 가능한가요?

**Comment by worldii** [comment]
장바구니 전체 조회할 시, 페이징을 적용할 것인지, 아니면 장바구니 수량을 제한할 것인지 토의해봐야할거같습니다~

**Comment by hwihwi523** [comment]
> 장바구니 등록은 하나씩 추가하는 구조인가요 여러개 추가도 가능한가요?

여러 개 추가로 결정되었습니다.

**Comment by hwihwi523** [comment]
> 장바구니 전체 조회할 시, 페이징을 적용할 것인지, 아니면 장바구니 수량을 제한할 것인지 토의해봐야할거같습니다~

장바구니에 담을 수 있는 품목의 개수를 최대 100개로 제한하는 것으로 결정되었습니다.

**Comment by whatasame** [comment]
closed by #37
