### ISSUE TITLE
ER diagram

### ISSUE THREAD

**Issue by whatasame** [woowatechcamp/soolsool#27]
## 📝 이슈 내용

ER diagram을 작성한다.

## ✅ 구현 사항

- [x] entity와 relation을 정의한다.
- [x] column 제약 사항을 정의한다.

## 📌 비고

local 환경이 아닌 cloud 환경에서 작성하여 접근성을 높인다.

**Comment by hwihwi523** [comment]
https://www.erdcloud.com/d/2YhJNNXRjNgqYrh7E
