### ISSUE TITLE
code convention 업데이트

### ISSUE THREAD

**Issue by whatasame** [woowatechcamp/soolsool#31]
## 📝 이슈 내용

code convention 수정으로 적용받는 코드를 수정한다.

## ✅ 구현 사항

- [x] final 키워드 적용
- [x] controller, service로 이름 변경

**Comment by jjungsk** [comment]
#37 : final 키워드 적용 완료 (by. 정규)

**Comment by whatasame** [comment]
완료! 

controller, service로 이름 변경은 [위키](https://github.com/woowatechcamp/soolsool/wiki/Code-convention#layer-naming) 참고
